name: Captain Hook
version: 0.1.0
description: >
  Captain Hook simplifies managing
  webhooks from third-party services.
url: lionsmouth.digital
developer: Curtis Blackwell
developer_url: lionsmouth.digital
